[package]
name = "task-cli"
version = "0.1.0"
authors = ["ninet33n <slipstreamvroom@gmail.com>"]
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
directories = "5.0"
